### ISSUE TITLE
无法生成藏头诗

### ISSUE THREAD

**Issue by first-wording** [HqWei/Automatic-creation-of-Tibetan-poetry-and-Tang-poetry#2]
你好，为什么我在运行生成藏头诗的程序时，没有显示藏头诗，只有以下结果
![issue](https://user-images.githubusercontent.com/46805548/59649537-a41d4300-91b5-11e9-9899-2a505f99ea94.png)

**Comment by frostbite-zhs** [comment]
最后的if语句中的main后面少了个_
